/**
 * Spotify 自动同步脚本（Plan B：GitHub Actions 每日运行）
 *
 * 1. 用 Client Credentials 获取 token（需要 SPOTIFY_CLIENT_ID / SPOTIFY_CLIENT_SECRET 环境变量）
 * 2. 按 scripts/spotify-artists.json 配置搜索每位艺人/小分队的 Spotify 页面
 * 3. 拉取其专辑 / 单曲的发行日期与完整曲目
 * 4. 写入 src/data/spotify-data.ts（内容无变化则不写，CI 便不会产生空提交）
 *
 * 数据在 src/data/mergeSpotify.ts 中与人工维护的 albums.ts 合并：
 *  - 已有专辑：按标题匹配后更新曲目列表 / 发行日期 / 待公布的主打曲
 *  - 新发行（近 90 天内或未来发行）：自动追加为新区块条目
 *
 * 首次运行请检查控制台输出的 [match] 日志，确认搜索到的艺人正确；
 * 如有偏差，把正确的 Spotify 艺人 ID 填进配置的 "spotifyArtistId" 字段锁定。
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT_FILE = path.join(ROOT, 'src', 'data', 'spotify-data.ts');
const CONFIG_FILE = path.join(ROOT, 'scripts', 'spotify-artists.json');

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;
if (!CLIENT_ID || !CLIENT_SECRET) {
  console.error('[spotify-sync] 缺少 SPOTIFY_CLIENT_ID / SPOTIFY_CLIENT_SECRET 环境变量');
  process.exit(1);
}

async function getToken() {
  const res = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: 'Basic ' + Buffer.from(CLIENT_ID + ':' + CLIENT_SECRET).toString('base64'),
    },
    body: 'grant_type=client_credentials',
  });
  if (!res.ok) throw new Error('获取 token 失败: HTTP ' + res.status);
  const j = await res.json();
  return j.access_token;
}

async function api(url, token) {
  const res = await fetch(url, { headers: { Authorization: 'Bearer ' + token } });
  if (!res.ok) throw new Error('API 请求失败 ' + url + ' -> HTTP ' + res.status);
  return res.json();
}

async function searchArtist(q, token) {
  const j = await api('https://api.spotify.com/v1/search?type=artist&limit=1&q=' + encodeURIComponent(q), token);
  return j.artists.items[0] ?? null;
}

async function artistReleases(id, token) {
  let url = `https://api.spotify.com/v1/artists/${id}/albums?include_groups=album,single&limit=50`;
  const items = [];
  while (url) {
    const j = await api(url, token);
    items.push(...j.items);
    url = j.next;
  }
  return items;
}

const MAX_PER_ARTIST = 25;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const token = await getToken();
  const config = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
  const releases = [];

  for (const entry of config.artists) {
    let artist = null;
    if (entry.spotifyArtistId) {
      artist = await api(`https://api.spotify.com/v1/artists/${entry.spotifyArtistId}`, token);
    } else {
      artist = await searchArtist(entry.search, token);
    }
    if (!artist) {
      console.warn(`[spotify-sync] 未找到艺人: ${entry.key} (search: ${entry.search})`);
      continue;
    }
    console.log(`[match] ${entry.key} -> ${artist.name} (${artist.id})`);

    const albums = (await artistReleases(artist.id, token))
      .filter((a) => a.album_group !== 'compilation' && a.album_type !== 'compilation')
      .sort((a, b) => (b.release_date ?? '').localeCompare(a.release_date ?? ''))
      .slice(0, MAX_PER_ARTIST);

    for (const al of albums) {
      await sleep(80); // 温和限速
      const detail = await api(`https://api.spotify.com/v1/albums/${al.id}`, token);
      const rd = detail.release_date;
      if (!/^\d{4}-\d{2}-\d{2}$/.test(rd)) continue; // 跳过无法精确到日的发行
      releases.push({
        bucket: entry.bucket,
        artist: entry.bucket === 'group' ? undefined : entry.key,
        spotifyAlbumId: al.id,
        title: al.name,
        spotifyType: detail.album_type,
        releaseDate: rd,
        tracks: detail.tracks.items.map((t) => t.name),
      });
    }
  }

  const payload = { syncedAt: new Date().toISOString(), releases };
  const content =
    '// AUTO-GENERATED by scripts/sync-spotify.mjs — 请勿手动编辑\n' +
    'export const spotifySync = ' + JSON.stringify(payload, null, 2) + ';\n';

  const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, 'utf8') : '';
  if (prev === content) {
    console.log('[spotify-sync] 数据无变化，不写入文件');
    return;
  }
  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log(`[spotify-sync] 已写入 ${OUT_FILE}（${releases.length} 条发行记录）`);
}

main().catch((e) => {
  console.error('[spotify-sync] 同步失败:', e);
  process.exit(1);
});
