// AUTO-GENERATED by scripts/sync-spotify.mjs — 请勿手动编辑
// 当前为占位数据（尚未同步）。GitHub Actions 配置 SPOTIFY_CLIENT_ID / SPOTIFY_CLIENT_SECRET 后每日自动更新。
export const spotifySync = {
  syncedAt: null,
  releases: [],
};
